using System.Collections.Generic;
using UnityEngine;
using Photon.Pun;

public class PlayerController : MonoBehaviourPunCallbacks
{
    public Transform viewPoint;//ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ÌˆÊ’uï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½g
    public float mouseSensitivity = 1f;//ï¿½ï¿½ï¿½_ï¿½Ú“ï¿½ï¿½Ì‘ï¿½ï¿½x
    private Vector2 mouseInput;//ï¿½ï¿½ï¿½[ï¿½Uï¿½[ï¿½Ìƒ}ï¿½Eï¿½Xï¿½ï¿½ï¿½Í‚ï¿½ï¿½iï¿½[
    private float verticalMouseInput;//yï¿½ï¿½ï¿½Ì‰ï¿½]ï¿½ï¿½ï¿½iï¿½[ï¿½@ï¿½ï¿½]ï¿½ğ§Œï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    private Camera cam;//ï¿½Jï¿½ï¿½ï¿½ï¿½


    Animator animator;
    [SerializeField] private Rigidbody _rigidbody;



    private Vector3 moveDir;//ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½Ì“ï¿½ï¿½Í‚ï¿½ï¿½iï¿½[ï¿½iï¿½Ú“ï¿½ï¿½j
    private Vector3 movement;//ï¿½iï¿½Ş•ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½iï¿½[ï¿½ï¿½ï¿½ï¿½Ïï¿½
    private float activeMoveSpeed = 4;//ï¿½ï¿½ï¿½Û‚ÌˆÚ“ï¿½ï¿½ï¿½ï¿½x



    public Vector3 jumpForce = new Vector3(0, 6, 0);//ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ 
    public Transform groundCheckPoint;//ï¿½nï¿½Ê‚ÉŒï¿½ï¿½ï¿½ï¿½Äƒï¿½ï¿½Cï¿½ï¿½ï¿½Î‚ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½g 
    public LayerMask groundLayers;//ï¿½nï¿½Ê‚ï¿½ï¿½Æ”Fï¿½ï¿½ï¿½ï¿½ï¿½éƒŒï¿½Cï¿½ï¿½ï¿½[ 
    Rigidbody rb;//


    public float stopSpeed = 0 ,walkSpeed = 4, runSpeed = 8;//ï¿½ï¿½ï¿½ï¿½ï¿½Ì‘ï¿½ï¿½xï¿½Aï¿½ï¿½ï¿½ï¿½Ì‘ï¿½ï¿½x


    private bool cursorLock = true;//ï¿½Jï¿½[ï¿½\ï¿½ï¿½ï¿½Ì•\ï¿½ï¿½/ï¿½ï¿½\ï¿½ï¿½ 


    public List<Gun> guns = new List<Gun>();//ï¿½ï¿½ï¿½ï¿½ÌŠiï¿½[ï¿½zï¿½ï¿½
    private int selectedGun = 0;//ï¿½Iï¿½ğ’†‚Ì•ï¿½ï¿½ï¿½Ç—ï¿½ï¿½pï¿½ï¿½ï¿½l


    private float shotTimer;//ï¿½ËŒï¿½ï¿½ÔŠu
    [Tooltip("ï¿½ï¿½ï¿½ï¿½ï¿½eï¿½ï¿½")]
    public int[] ammunition;
    [Tooltip("ï¿½Åï¿½ï¿½ï¿½ï¿½ï¿½ï¿½eï¿½ï¿½")]
    public int[] maxAmmunition;
    [Tooltip("ï¿½}ï¿½Kï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½Ì’eï¿½ï¿½")]
    public int[] ammoClip;
    [Tooltip("ï¿½}ï¿½Kï¿½Wï¿½ï¿½ï¿½É“ï¿½ï¿½ï¿½Å‘ï¿½Ìï¿½")]
    public int[] maxAmmoClip;


    UIManager uIManager;//UIï¿½Ç—ï¿½


    SpawnManager spawnManager;//ï¿½Xï¿½|ï¿½[ï¿½ï¿½ï¿½}ï¿½lï¿½[ï¿½Wï¿½ï¿½ï¿½[ï¿½Ç—ï¿½

    AnimationClip nowAnimation;

    Dictionary<AnimationClip, float> Motion_Damage;

    private void Awake()
    {
        //ï¿½^ï¿½Oï¿½ï¿½ï¿½ï¿½UIManagerï¿½ï¿½Tï¿½ï¿½
        uIManager = GameObject.FindGameObjectWithTag("UIManager").GetComponent<UIManager>();

        //ï¿½^ï¿½Oï¿½ï¿½ï¿½ï¿½SpawnManagerï¿½ï¿½Tï¿½ï¿½
        spawnManager = GameObject.FindGameObjectWithTag("SpawnManager").GetComponent<SpawnManager>();

        animator = GetComponent<Animator>();

        string[] attackAnimationNames = { "Female Sword Attack 1" , "Female Sword Attack 2", "Female Sword Attack 3" };
        float[] damages = { 10, 15, 20 };

        Dictionary<string, float> a = new Dictionary<string, float>();
        for (int i = 0; i < damages.Length; i++)
            a.Add(attackAnimationNames[i], damages[i]);

        Motion_Damage = new Dictionary<AnimationClip, float>();

        var animation_clips = animator.runtimeAnimatorController.animationClips;
        var animation_names = new List<string>();

        foreach(var e in animator.runtimeAnimatorController.animationClips)
        {
            foreach(var n in attackAnimationNames)
            {
                if (e.ToString().Contains(n))
                {
                    Debug.Log(e.ToString() + "ã¯ã‚ã£ã¦ã‚ã¾ã—ãŸ");
                    Motion_Damage.Add(e, a[n]);
                }
            }
        }
    }

    private void Start()
    {
        _rigidbody = this.GetComponent<Rigidbody> ();

        //ï¿½Ïï¿½ï¿½Éƒï¿½ï¿½Cï¿½ï¿½ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½iï¿½[
        cam = Camera.main;


        //Rigidbodyï¿½ï¿½ï¿½iï¿½[
        rb = GetComponent<Rigidbody>();


        //ï¿½Jï¿½[ï¿½\ï¿½ï¿½ï¿½ï¿½\ï¿½ï¿½
        UpdateCursorLock();


        //ï¿½eï¿½ï¿½eï¿½Lï¿½Xï¿½gï¿½Xï¿½V
        uIManager.SettingBulletsText(ammoClip[selectedGun], ammunition[selectedGun]);

        this.animator = GetComponent<Animator>();

        nowAnimation = animator.GetCurrentAnimatorClipInfo(0)[0].clip;

        //ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½ÈˆÊ’uï¿½ÅƒXï¿½|ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        //transform.position = spawnManager.GetSpawnPoint().position;
    }

    private void Update() 
    {
        //ï¿½ï¿½ï¿½ï¿½ï¿½ÈŠOï¿½ï¿½
        if (!photonView.IsMine)
        {
            //ï¿½ß‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½È~ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½È‚ï¿½
            return;
        }

        nowAnimation = animator.GetCurrentAnimatorClipInfo(0)[0].clip;

        Attack();

        //ï¿½ï¿½ï¿½_ï¿½Ú“ï¿½ï¿½Öï¿½
        PlayerRotate();

        //ï¿½Ú“ï¿½ï¿½Öï¿½
        PlayerMove();

        //ï¿½nï¿½Ê‚É‚Â‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Ì‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        if (IsGround())
        {
            //ï¿½ï¿½ï¿½ï¿½ÌŠÖï¿½ï¿½ï¿½ï¿½Ä‚ï¿½
            Run();

            //ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½Öï¿½ï¿½ï¿½ï¿½Ä‚ï¿½
            Jump();
        }

        //ï¿½eï¿½ÌØ‚ï¿½Ö‚ï¿½
        SwitchingGuns();

        //ï¿½`ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        Aim();

        //ï¿½ËŒï¿½ï¿½Öï¿½
        Fire();

        //ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½hï¿½Öï¿½
        Reload();

        //ï¿½Jï¿½[ï¿½\ï¿½ï¿½ï¿½ï¿½\ï¿½ï¿½
        UpdateCursorLock();
    }

    //Updateï¿½Öï¿½ï¿½ï¿½ï¿½Ä‚Î‚ê‚½ï¿½ï¿½Éï¿½ï¿½sï¿½ï¿½ï¿½ï¿½ï¿½
    private void LateUpdate()
    {
        //ï¿½ï¿½ï¿½ï¿½ï¿½ÈŠOï¿½ï¿½
        if (!photonView.IsMine)
        {
            //ï¿½ß‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½È~ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½È‚ï¿½
            return;
        }

        //ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½Ìqï¿½É‚ï¿½ï¿½ï¿½Ì‚Å‚Í‚È‚ï¿½ï¿½Aï¿½Xï¿½Nï¿½ï¿½ï¿½vï¿½gï¿½ÅˆÊ’uï¿½ï¿½ï¿½ï¿½ï¿½í‚¹ï¿½ï¿½
        cam.transform.position = viewPoint.position;
        cam.transform.rotation = viewPoint.rotation;
    }

    //ï¿½ï¿½ï¿½ï¿½ï¿½İ’ï¿½Å‚ï¿½0.02ï¿½bï¿½ï¿½ï¿½Æ‚ÉŒÄ‚Î‚ï¿½ï¿½
    private void FixedUpdate()
    {
        //ï¿½ï¿½ï¿½ï¿½ï¿½ÈŠOï¿½ï¿½
        if (!photonView.IsMine)
        {
            //ï¿½ß‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½È~ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½È‚ï¿½
            return;
        }

        //ï¿½eï¿½ï¿½eï¿½Lï¿½Xï¿½gï¿½Xï¿½V
        uIManager.SettingBulletsText(ammoClip[selectedGun], ammunition[selectedGun]);
    }

    /// <summary>
    /// Playerï¿½Ì‰ï¿½ï¿½ï¿½]ï¿½Æcï¿½Ìï¿½ï¿½_ï¿½Ú“ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½
    /// </summary>
    public void PlayerRotate()
    {
        //ï¿½Ïï¿½ï¿½Éƒï¿½ï¿½[ï¿½Uï¿½[ï¿½Ìƒ}ï¿½Eï¿½Xï¿½Ì“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½iï¿½[
        mouseInput = new Vector2(Input.GetAxisRaw("Mouse X") * mouseSensitivity,
            Input.GetAxisRaw("Mouse Y") * mouseSensitivity);

        //ï¿½ï¿½ï¿½ï¿½]ï¿½ğ”½‰f(transform.eulerAnglesï¿½ÍƒIï¿½Cï¿½ï¿½ï¿½[ï¿½pï¿½Æ‚ï¿½ï¿½Ä‚ÌŠpï¿½xï¿½ï¿½ï¿½Ô‚ï¿½ï¿½ï¿½ï¿½)
        transform.rotation = Quaternion.Euler
            (transform.eulerAngles.x,
            transform.eulerAngles.y + mouseInput.x, //ï¿½}ï¿½Eï¿½Xï¿½ï¿½xï¿½ï¿½ï¿½Ì“ï¿½ï¿½Í‚ğ‘«‚ï¿½
            transform.eulerAngles.z);


        //ï¿½Ïï¿½ï¿½ï¿½yï¿½ï¿½ï¿½Ìƒ}ï¿½Eï¿½Xï¿½ï¿½ï¿½Í•ï¿½ï¿½Ìï¿½ï¿½lï¿½ğ‘«‚ï¿½
        verticalMouseInput += mouseInput.y;

        //ï¿½Ïï¿½ï¿½Ìï¿½ï¿½lï¿½ï¿½ï¿½Û‚ß‚ï¿½iï¿½ã‰ºï¿½Ìï¿½ï¿½_ï¿½ï¿½ï¿½ï¿½j
        verticalMouseInput = Mathf.Clamp(verticalMouseInput, -60f, 60f);

        //ï¿½cï¿½Ìï¿½ï¿½_ï¿½ï¿½]ï¿½ğ”½‰f(-ï¿½ï¿½tï¿½ï¿½ï¿½È‚ï¿½ï¿½Æã‰ºï¿½ï¿½ï¿½]ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½Ü‚ï¿½)
        viewPoint.rotation = Quaternion.Euler
            (-verticalMouseInput,
            viewPoint.transform.rotation.eulerAngles.y,
            viewPoint.transform.rotation.eulerAngles.z);
    }



    /// <summary>
    /// Playerï¿½ÌˆÚ“ï¿½
    /// </summary>
    public void PlayerMove()
    {
        //ï¿½Ïï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½Æï¿½ï¿½ï¿½ï¿½Ì“ï¿½ï¿½Í‚ï¿½ï¿½iï¿½[ï¿½ï¿½ï¿½ï¿½iwasdï¿½ï¿½ï¿½ï¿½Ì“ï¿½ï¿½Íj
        moveDir = new Vector3(Input.GetAxisRaw("Horizontal"),
            0, Input.GetAxisRaw("Vertical"));

        //Debug.Log(moveDir);ï¿½ï¿½ï¿½ï¿½ï¿½p

        //ï¿½Qï¿½[ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ì‚ï¿½ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½É“ï¿½ï¿½Í‚ï¿½ï¿½ê‚½ï¿½lï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æiï¿½Ş•ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½oï¿½ï¿½ï¿½ï¿½
        movement = ((transform.forward * moveDir.z) + (transform.right * moveDir.x)).normalized;

        //ï¿½ï¿½ï¿½İˆÊ’uï¿½Éiï¿½Ş•ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ú“ï¿½ï¿½Xï¿½sï¿½[ï¿½hï¿½ï¿½ï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½Ô•bï¿½ï¿½ï¿½ğ‘«‚ï¿½
        transform.position += movement * activeMoveSpeed * Time.deltaTime;
    }


    /// <summary>
    /// ï¿½nï¿½Ê‚É‚Â‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½È‚ï¿½true
    /// </summary>
    /// <returns></returns>
    public bool IsGround()
    {
        return Physics.Raycast(groundCheckPoint.position, Vector3.down, 0.5f, groundLayers);
    }


    public void Jump()
    {
        //ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½Å‚ï¿½ï¿½ï¿½Ì‚ï¿½ï¿½ï¿½ï¿½ï¿½
        if (IsGround() && Input.GetKeyDown(KeyCode.Space))
        {
            //ï¿½uï¿½Ô“Iï¿½É^ï¿½ï¿½É—Í‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            rb.AddForce(jumpForce, ForceMode.Impulse);
            animator.SetBool("jump", true);
        }else{
            animator.SetBool("jump", false);
        }
    }


    public void Run()
    {
        if (nowAnimation.name.Contains("Attack"))
        {
            activeMoveSpeed = 0f;
            return;
        }

        //ï¿½ï¿½ï¿½Vï¿½tï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½ÍƒXï¿½sï¿½[ï¿½hï¿½ï¿½Ø‚ï¿½Ö‚ï¿½ï¿½ï¿½
        if (Input.GetKey(KeyCode.A) || Input.GetKey(KeyCode.D) || Input.GetKey(KeyCode.S) || Input.GetKey(KeyCode.W))
        {
            if (Input.GetKey(KeyCode.LeftShift))
            {
                activeMoveSpeed = runSpeed;
            }
            else
            {
                activeMoveSpeed = walkSpeed;
            }
        }
        else
        {
            activeMoveSpeed = stopSpeed;
        }
        animator.SetFloat("speed", activeMoveSpeed);
    }



    public void UpdateCursorLock()
    {
        //ï¿½ï¿½ï¿½Í‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½cursorLockï¿½ï¿½Ø‚ï¿½Ö‚ï¿½ï¿½ï¿½
        if (Input.GetKeyDown(KeyCode.Escape))
        {
            cursorLock = false;
        }
        else if (Input.GetMouseButton(0))
        {
            cursorLock = true;
        }

        //cursorLockï¿½ï¿½ï¿½ï¿½ÅƒJï¿½[ï¿½\ï¿½ï¿½ï¿½Ì•\ï¿½ï¿½ï¿½ï¿½Ø‚ï¿½Ö‚ï¿½ï¿½ï¿½
        if (cursorLock)
        {
            //ï¿½Jï¿½[ï¿½\ï¿½ï¿½ï¿½ğ’†‰ï¿½ï¿½ÉŒÅ’è‚µï¿½Aï¿½ï¿½\ï¿½ï¿½ï¿½@https://docs.unity3d.com/ScriptReference/CursorLockMode.html
            Cursor.lockState = CursorLockMode.Locked;
        }
        else
        {
            //ï¿½\ï¿½ï¿½
            Cursor.lockState = CursorLockMode.None;
        }
    }


    /// <summary>
    /// ï¿½eï¿½ÌØ‚ï¿½Ö‚ï¿½ï¿½Lï¿½[ï¿½ï¿½ï¿½Í‚ï¿½ï¿½ï¿½ï¿½mï¿½ï¿½ï¿½ï¿½
    /// </summary>
    public void SwitchingGuns()
    {
        if (Input.GetAxisRaw("Mouse ScrollWheel") > 0f)
        {
            selectedGun++;//ï¿½ï¿½ï¿½ï¿½ï¿½eï¿½ï¿½ï¿½Ç—ï¿½ï¿½ï¿½ï¿½é”ï¿½lï¿½ğ‘‚â‚·

            //ï¿½ï¿½ï¿½Xï¿½gï¿½ï¿½ï¿½å‚«ï¿½ï¿½ï¿½ï¿½ï¿½lï¿½É‚È‚ï¿½ï¿½Ä‚ï¿½ï¿½È‚ï¿½ï¿½ï¿½ï¿½mï¿½F
            if (selectedGun >= guns.Count)
            {
                selectedGun = 0;//ï¿½ï¿½ï¿½Xï¿½gï¿½ï¿½ï¿½å‚«ï¿½Èï¿½ï¿½lï¿½É‚È‚ï¿½Î‚Oï¿½É–ß‚ï¿½
            }
            switchGun();
        }
        else if (Input.GetAxisRaw("Mouse ScrollWheel") < 0f)
        {
            selectedGun--;//ï¿½ï¿½ï¿½ï¿½ï¿½eï¿½ï¿½ï¿½Ç—ï¿½ï¿½ï¿½ï¿½é”ï¿½lï¿½ï¿½ï¿½ï¿½ï¿½ç‚·


            if (selectedGun < 0)
            {
                selectedGun = guns.Count - 1;//0ï¿½ï¿½è¬ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Îƒï¿½ï¿½Xï¿½gï¿½ÌÅ‘å”ï¿½|ï¿½Pï¿½Ìï¿½ï¿½lï¿½Éİ’è‚·ï¿½ï¿½
            }

            //ï¿½ï¿½ï¿½Û‚É•ï¿½ï¿½ï¿½ï¿½Ø‚ï¿½Ö‚ï¿½ï¿½ï¿½Öï¿½
            switchGun();
        }

        //ï¿½ï¿½ï¿½lï¿½Lï¿½[ï¿½Ì“ï¿½ï¿½ÍŒï¿½ï¿½mï¿½Å•ï¿½ï¿½ï¿½ï¿½Ø‚ï¿½Ö‚ï¿½ï¿½ï¿½
        for (int i = 0; i < guns.Count; i++)
        {
            if (Input.GetKeyDown((i + 1).ToString()))//ï¿½ï¿½ï¿½[ï¿½vï¿½Ìï¿½ï¿½lï¿½{ï¿½Pï¿½ï¿½ï¿½ï¿½ï¿½Ä•ï¿½ï¿½ï¿½ï¿½ï¿½É•ÏŠï¿½ï¿½Bï¿½ï¿½ï¿½ÌŒï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½ê‚½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            {
                selectedGun = i;//ï¿½eï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½lï¿½ï¿½İ’ï¿½

                //ï¿½ï¿½ï¿½Û‚É•ï¿½ï¿½ï¿½ï¿½Ø‚ï¿½Ö‚ï¿½ï¿½ï¿½Öï¿½
                switchGun();

            }
        }
    }

    /// <summary>
    /// ï¿½eï¿½ÌØ‚ï¿½Ö‚ï¿½
    /// </summary>
    void switchGun()
    {
        foreach (Gun gun in guns)//ï¿½ï¿½ï¿½Xï¿½gï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½vï¿½ï¿½ï¿½ï¿½
        {
            gun.gameObject.SetActive(false);//ï¿½eï¿½ï¿½ï¿½\ï¿½ï¿½
        }

        guns[selectedGun].gameObject.SetActive(true);//ï¿½Iï¿½ğ’†‚Ìeï¿½Ì‚İ•\ï¿½ï¿½
    }



    /// <summary>
    /// ï¿½Eï¿½Nï¿½ï¿½ï¿½bï¿½Nï¿½Å”`ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    /// </summary>
    public void Aim()
    {
        //  ï¿½}ï¿½Eï¿½Xï¿½Eï¿½{ï¿½^ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Æ‚ï¿½
        if (Input.GetMouseButton(1))
        {
            //fieldOfViewï¿½Rï¿½ï¿½ï¿½|ï¿½[ï¿½lï¿½ï¿½ï¿½gï¿½Ì’lï¿½ï¿½ÏX(ï¿½Jï¿½nï¿½nï¿½_ï¿½Aï¿½Ú“Iï¿½nï¿½_ï¿½Aï¿½âŠ®ï¿½ï¿½ï¿½l)ï¿½@ï¿½@ï¿½Jï¿½nï¿½nï¿½_ï¿½ï¿½ï¿½ï¿½Ú“Iï¿½nï¿½_ï¿½Ü‚Å•âŠ®ï¿½ï¿½ï¿½lï¿½ÌŠï¿½ï¿½ï¿½ï¿½Åï¿½ï¿½Xï¿½É‹ß‚Ã‚ï¿½ï¿½ï¿½
            cam.fieldOfView = Mathf.Lerp(cam.fieldOfView, guns[selectedGun].adsZoom, guns[selectedGun].adsSpeed * Time.deltaTime);
        }
        else
        {   //60ï¿½Íï¿½ï¿½ï¿½ï¿½İ’è”ï¿½l
            cam.fieldOfView = Mathf.Lerp(cam.fieldOfView, 60f, guns[selectedGun].adsSpeed * Time.deltaTime);
        }
    }



    /// <summary>
    /// ï¿½ï¿½ï¿½Nï¿½ï¿½ï¿½bï¿½Nï¿½ÌŒï¿½ï¿½m
    /// </summary>
    public void Fire()
    {

        if (Input.GetMouseButton(0) && ammoClip[selectedGun] > 0 && Time.time > shotTimer)
        {
            FiringBullet();
        }

    }

    /// <summary>
    /// ï¿½eï¿½Û‚Ì”ï¿½ï¿½ï¿½
    /// </summary>
    private void FiringBullet()
    {
        //ï¿½Iï¿½ğ’†‚Ìeï¿½Ì’eï¿½òŒ¸‚ç‚·
        ammoClip[selectedGun]--;

        //Ray(ï¿½ï¿½ï¿½ï¿½)ï¿½ï¿½ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½Ì’ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Éİ’ï¿½
        Ray ray = cam.ViewportPointToRay(new Vector2(.5f, .5f));//ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½Ì’ï¿½ï¿½Sï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½l


        //ï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½Î‚ï¿½ï¿½iï¿½Jï¿½nï¿½nï¿½_ï¿½Æ•ï¿½ï¿½ï¿½ï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Rï¿½ï¿½ï¿½Cï¿½_ï¿½[ï¿½Ìï¿½ï¿½iï¿½[ï¿½j
        if (Physics.Raycast(ray, out RaycastHit hit))
        {
            //Debug.Log("ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½" + hit.collider.gameObject.name);

            //ï¿½eï¿½ï¿½ï¿½Gï¿½tï¿½Fï¿½Nï¿½g (hit.pointï¿½ÍƒRï¿½ï¿½ï¿½Cï¿½_ï¿½[ï¿½Éƒqï¿½bï¿½gï¿½ï¿½ï¿½ï¿½ï¿½Ê’u)ï¿½Fhit.point + (hit.normal * .002f)ï¿½Í‚ï¿½ï¿½ï¿½Â‚ï¿½ï¿½È‚ï¿½ï¿½æ‚¤ï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½É‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½
            //hit normalï¿½Í“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½É‘Î‚ï¿½ï¿½Ä’ï¿½ï¿½pï¿½Ì•ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ô‚ï¿½ï¿½ï¿½ï¿½
            //LookRotationï¿½Íwï¿½è‚µï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É‰ï¿½
            GameObject bulletImpactObject = Instantiate(guns[selectedGun].bulletImpact, hit.point + (hit.normal * .002f), Quaternion.LookRotation(hit.normal, Vector3.up));

            //ï¿½ï¿½ï¿½ÔŒoï¿½ß‚Åï¿½ï¿½ï¿½ï¿½ï¿½æ‚¤ï¿½É‚ï¿½ï¿½ï¿½
            Destroy(bulletImpactObject, 10f);
        }

        //ï¿½ËŒï¿½ï¿½ÔŠuï¿½ï¿½İ’ï¿½
        shotTimer = Time.time + guns[selectedGun].shootInterval;


    }


    /// <summary>
    /// ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½h
    /// </summary>
    private void Reload()
    {
        if (Input.GetKeyDown(KeyCode.R))
        {
            //ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½hï¿½Å•ï¿½[ï¿½ï¿½ï¿½ï¿½eï¿½ï¿½ï¿½ï¿½ï¿½æ“¾ï¿½ï¿½ï¿½ï¿½
            int amountNeed = maxAmmoClip[selectedGun] - ammoClip[selectedGun];

            //ï¿½Kï¿½vï¿½È’eï¿½ï¿½Ê‚Æï¿½ï¿½ï¿½ï¿½eï¿½ï¿½Ê‚ï¿½ï¿½r
            int ammoAvailable = amountNeed < ammunition[selectedGun] ? amountNeed : ammunition[selectedGun];

            //ï¿½eï¿½ò‚ª–ï¿½ï¿½^ï¿½ï¿½ï¿½Ìï¿½ï¿½Íƒï¿½ï¿½ï¿½ï¿½[ï¿½hï¿½Å‚ï¿½ï¿½È‚ï¿½&ï¿½eï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Æ‚ï¿½
            if (amountNeed != 0 && ammunition[selectedGun] != 0)
            {
                //ï¿½ï¿½ï¿½ï¿½ï¿½eï¿½ò‚©‚çƒŠï¿½ï¿½ï¿½[ï¿½hï¿½ï¿½ï¿½ï¿½eï¿½ò•ª‚ï¿½ï¿½ï¿½ï¿½ï¿½
                ammunition[selectedGun] -= ammoAvailable;
                //ï¿½eï¿½É‘ï¿½ï¿½Uï¿½ï¿½ï¿½ï¿½
                ammoClip[selectedGun] += ammoAvailable;
            }
        }
    }

    private void Attack()
    {
        animator.SetBool("Attack", Input.GetMouseButton(0));
    }



    public float GetDamage(AnimationClip hitAttack)
    {
        float damage;
        if (!Motion_Damage.TryGetValue(hitAttack, out damage)) 
            damage = -1;

        return damage;
    }


}