using System.Collections.Generic;
using UnityEngine;
using Photon.Pun;

public class PlayerController : MonoBehaviourPunCallbacks
{
    public Transform viewPoint;//ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ÌˆÊ’uï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½g
    public float mouseSensitivity = 1f;//ï¿½ï¿½ï¿½_ï¿½Ú“ï¿½ï¿½Ì‘ï¿½ï¿½x
    private Vector2 mouseInput;//ï¿½ï¿½ï¿½[ï¿½Uï¿½[ï¿½Ìƒ}ï¿½Eï¿½Xï¿½ï¿½ï¿½Í‚ï¿½ï¿½iï¿½[
    private float verticalMouseInput;//yï¿½ï¿½ï¿½Ì‰ï¿½]ï¿½ï¿½ï¿½iï¿½[ï¿½@ï¿½ï¿½]ï¿½ğ§Œï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    private Camera cam;//ï¿½Jï¿½ï¿½ï¿½ï¿½
    Animator animator;
    [SerializeField] private Rigidbody _rigidbody;

    private Vector3 moveDir;//ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½Ì“ï¿½ï¿½Í‚ï¿½ï¿½iï¿½[ï¿½iï¿½Ú“ï¿½ï¿½j
    private Vector3 movement;//ï¿½iï¿½Ş•ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½iï¿½[ï¿½ï¿½ï¿½ï¿½Ïï¿½
    private float activeMoveSpeed = 4;//ï¿½ï¿½ï¿½Û‚ÌˆÚ“ï¿½ï¿½ï¿½ï¿½x

    public Vector3 jumpForce = new Vector3(0, 6, 0);//ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ 
    public Transform groundCheckPoint;//ï¿½nï¿½Ê‚ÉŒï¿½ï¿½ï¿½ï¿½Äƒï¿½ï¿½Cï¿½ï¿½ï¿½Î‚ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½g 
    public LayerMask groundLayers;//ï¿½nï¿½Ê‚ï¿½ï¿½Æ”Fï¿½ï¿½ï¿½ï¿½ï¿½éƒŒï¿½Cï¿½ï¿½ï¿½[ 
    Rigidbody rb;//

    public float stopSpeed = 0 ,walkSpeed = 4, runSpeed = 8;//ï¿½ï¿½ï¿½ï¿½ï¿½Ì‘ï¿½ï¿½xï¿½Aï¿½ï¿½ï¿½ï¿½Ì‘ï¿½ï¿½x

    private bool cursorLock = true;//ï¿½Jï¿½[ï¿½\ï¿½ï¿½ï¿½Ì•\ï¿½ï¿½/ï¿½ï¿½\ï¿½ï¿½ 

    [Tooltip("ï¿½ï¿½ï¿½ï¿½ï¿½eï¿½ï¿½")]
    public int[] ammunition;
    [Tooltip("ï¿½Åï¿½ï¿½ï¿½ï¿½ï¿½ï¿½eï¿½ï¿½")]
    public int[] maxAmmunition;
    [Tooltip("ï¿½}ï¿½Kï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½Ì’eï¿½ï¿½")]
    public int[] ammoClip;
    [Tooltip("ï¿½}ï¿½Kï¿½Wï¿½ï¿½ï¿½É“ï¿½ï¿½ï¿½Å‘ï¿½Ìï¿½")]
    public int[] maxAmmoClip;


    UIManager uIManager;//UIï¿½Ç—ï¿½


    SpawnManager spawnManager;//ï¿½Xï¿½|ï¿½[ï¿½ï¿½ï¿½}ï¿½lï¿½[ï¿½Wï¿½ï¿½ï¿½[ï¿½Ç—ï¿½

    AnimationClip nowAnimation;

    Dictionary<AnimationClip, float> Motion_Damage;

    private readonly string[] attackAnimationNames = { "Female Sword Attack 1", "Female Sword Attack 2", "Female Sword Attack 3" };
    private readonly float[] damages = { 10, 15, 20 };

    private void Awake()
    {
        //ï¿½^ï¿½Oï¿½ï¿½ï¿½ï¿½UIManagerï¿½ï¿½Tï¿½ï¿½
        uIManager = GameObject.FindGameObjectWithTag("UIManager").GetComponent<UIManager>();

        //ï¿½^ï¿½Oï¿½ï¿½ï¿½ï¿½SpawnManagerï¿½ï¿½Tï¿½ï¿½
        spawnManager = GameObject.FindGameObjectWithTag("SpawnManager").GetComponent<SpawnManager>();

        animator = GetComponent<Animator>();


        Dictionary<string, float> a = new Dictionary<string, float>();
        for (int i = 0; i < damages.Length; i++)
            a.Add(attackAnimationNames[i], damages[i]);

        Motion_Damage = new Dictionary<AnimationClip, float>();

        foreach(var animClip in animator.runtimeAnimatorController.animationClips)
        {
            foreach(var animationName in attackAnimationNames)
            {
                if (animClip.ToString().Contains(animationName))
                {
                    Debug.Log(animClip.ToString() + "ã¯ã‚ã£ã¦ã‚ã¾ã—ãŸ");
                    Motion_Damage.Add(animClip, a[animationName]);
                }
            }
        }
    }

    private void Start()
    {
        _rigidbody = this.GetComponent<Rigidbody> ();

        //ï¿½Ïï¿½ï¿½Éƒï¿½ï¿½Cï¿½ï¿½ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½iï¿½[
        cam = Camera.main;


        //Rigidbodyï¿½ï¿½ï¿½iï¿½[
        rb = GetComponent<Rigidbody>();


        //ï¿½Jï¿½[ï¿½\ï¿½ï¿½ï¿½ï¿½\ï¿½ï¿½
        UpdateCursorLock();


        //ï¿½eï¿½ï¿½eï¿½Lï¿½Xï¿½gï¿½Xï¿½V

        this.animator = GetComponent<Animator>();

        nowAnimation = animator.GetCurrentAnimatorClipInfo(0)[0].clip;

        //ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½ÈˆÊ’uï¿½ÅƒXï¿½|ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        //transform.position = spawnManager.GetSpawnPoint().position;
    }

    private void Update() 
    {
        //ï¿½ï¿½ï¿½ï¿½ï¿½ÈŠOï¿½ï¿½
        if (!photonView.IsMine)
        {
            //ï¿½ß‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½È~ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½È‚ï¿½
            return;
        }

        nowAnimation = animator.GetCurrentAnimatorClipInfo(0)[0].clip;

        Attack();

        //ï¿½ï¿½ï¿½_ï¿½Ú“ï¿½ï¿½Öï¿½
        PlayerRotate();

        //ï¿½Ú“ï¿½ï¿½Öï¿½
        PlayerMove();

        //ï¿½nï¿½Ê‚É‚Â‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Ì‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        if (IsGround())
        {
            //ï¿½ï¿½ï¿½ï¿½ÌŠÖï¿½ï¿½ï¿½ï¿½Ä‚ï¿½
            Run();

            //ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½Öï¿½ï¿½ï¿½ï¿½Ä‚ï¿½
            Jump();
        }


        //ï¿½Jï¿½[ï¿½\ï¿½ï¿½ï¿½ï¿½\ï¿½ï¿½
        UpdateCursorLock();
    }

    //Updateï¿½Öï¿½ï¿½ï¿½ï¿½Ä‚Î‚ê‚½ï¿½ï¿½Éï¿½ï¿½sï¿½ï¿½ï¿½ï¿½ï¿½
    private void LateUpdate()
    {
        //ï¿½ï¿½ï¿½ï¿½ï¿½ÈŠOï¿½ï¿½
        if (!photonView.IsMine)
        {
            //ï¿½ß‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½È~ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½È‚ï¿½
            return;
        }

        //ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½Ìqï¿½É‚ï¿½ï¿½ï¿½Ì‚Å‚Í‚È‚ï¿½ï¿½Aï¿½Xï¿½Nï¿½ï¿½ï¿½vï¿½gï¿½ÅˆÊ’uï¿½ï¿½ï¿½ï¿½ï¿½í‚¹ï¿½ï¿½
        cam.transform.position = viewPoint.position;
        cam.transform.rotation = viewPoint.rotation;
    }

    //ï¿½ï¿½ï¿½ï¿½ï¿½İ’ï¿½Å‚ï¿½0.02ï¿½bï¿½ï¿½ï¿½Æ‚ÉŒÄ‚Î‚ï¿½ï¿½
    private void FixedUpdate()
    {
        //ï¿½ï¿½ï¿½ï¿½ï¿½ÈŠOï¿½ï¿½
        if (!photonView.IsMine)
        {
            //ï¿½ß‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½È~ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½È‚ï¿½
            return;
        }

        //ï¿½eï¿½ï¿½eï¿½Lï¿½Xï¿½gï¿½Xï¿½V
    }

    /// <summary>
    /// Playerï¿½Ì‰ï¿½ï¿½ï¿½]ï¿½Æcï¿½Ìï¿½ï¿½_ï¿½Ú“ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½
    /// </summary>
    public void PlayerRotate()
    {
        //ï¿½Ïï¿½ï¿½Éƒï¿½ï¿½[ï¿½Uï¿½[ï¿½Ìƒ}ï¿½Eï¿½Xï¿½Ì“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½iï¿½[
        mouseInput = new Vector2(Input.GetAxisRaw("Mouse X") * mouseSensitivity,
            Input.GetAxisRaw("Mouse Y") * mouseSensitivity);

        //ï¿½ï¿½ï¿½ï¿½]ï¿½ğ”½‰f(transform.eulerAnglesï¿½ÍƒIï¿½Cï¿½ï¿½ï¿½[ï¿½pï¿½Æ‚ï¿½ï¿½Ä‚ÌŠpï¿½xï¿½ï¿½ï¿½Ô‚ï¿½ï¿½ï¿½ï¿½)
        transform.rotation = Quaternion.Euler
            (transform.eulerAngles.x,
            transform.eulerAngles.y + mouseInput.x, //ï¿½}ï¿½Eï¿½Xï¿½ï¿½xï¿½ï¿½ï¿½Ì“ï¿½ï¿½Í‚ğ‘«‚ï¿½
            transform.eulerAngles.z);


        //ï¿½Ïï¿½ï¿½ï¿½yï¿½ï¿½ï¿½Ìƒ}ï¿½Eï¿½Xï¿½ï¿½ï¿½Í•ï¿½ï¿½Ìï¿½ï¿½lï¿½ğ‘«‚ï¿½
        verticalMouseInput += mouseInput.y;

        //ï¿½Ïï¿½ï¿½Ìï¿½ï¿½lï¿½ï¿½ï¿½Û‚ß‚ï¿½iï¿½ã‰ºï¿½Ìï¿½ï¿½_ï¿½ï¿½ï¿½ï¿½j
        verticalMouseInput = Mathf.Clamp(verticalMouseInput, -60f, 60f);

        //ï¿½cï¿½Ìï¿½ï¿½_ï¿½ï¿½]ï¿½ğ”½‰f(-ï¿½ï¿½tï¿½ï¿½ï¿½È‚ï¿½ï¿½Æã‰ºï¿½ï¿½ï¿½]ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½Ü‚ï¿½)
        viewPoint.rotation = Quaternion.Euler
            (-verticalMouseInput,
            viewPoint.transform.rotation.eulerAngles.y,
            viewPoint.transform.rotation.eulerAngles.z);
    }



    /// <summary>
    /// Playerï¿½ÌˆÚ“ï¿½
    /// </summary>
    public void PlayerMove()
    {
        //ï¿½Ïï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½Æï¿½ï¿½ï¿½ï¿½Ì“ï¿½ï¿½Í‚ï¿½ï¿½iï¿½[ï¿½ï¿½ï¿½ï¿½iwasdï¿½ï¿½ï¿½ï¿½Ì“ï¿½ï¿½Íj
        moveDir = new Vector3(Input.GetAxisRaw("Horizontal"),
            0, Input.GetAxisRaw("Vertical"));

        //Debug.Log(moveDir);ï¿½ï¿½ï¿½ï¿½ï¿½p

        //ï¿½Qï¿½[ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ì‚ï¿½ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½É“ï¿½ï¿½Í‚ï¿½ï¿½ê‚½ï¿½lï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æiï¿½Ş•ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½oï¿½ï¿½ï¿½ï¿½
        movement = ((transform.forward * moveDir.z) + (transform.right * moveDir.x)).normalized;

        //ï¿½ï¿½ï¿½İˆÊ’uï¿½Éiï¿½Ş•ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ú“ï¿½ï¿½Xï¿½sï¿½[ï¿½hï¿½ï¿½ï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½Ô•bï¿½ï¿½ï¿½ğ‘«‚ï¿½
        transform.position += movement * activeMoveSpeed * Time.deltaTime;
    }


    /// <summary>
    /// ï¿½nï¿½Ê‚É‚Â‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½È‚ï¿½true
    /// </summary>
    /// <returns></returns>
    public bool IsGround()
    {
        return Physics.Raycast(groundCheckPoint.position, Vector3.down, 0.5f, groundLayers);
    }


    public void Jump()
    {
        //ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½Å‚ï¿½ï¿½ï¿½Ì‚ï¿½ï¿½ï¿½ï¿½ï¿½
        if (IsGround() && Input.GetKeyDown(KeyCode.Space))
        {
            //ï¿½uï¿½Ô“Iï¿½É^ï¿½ï¿½É—Í‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            rb.AddForce(jumpForce, ForceMode.Impulse);
            animator.SetBool("jump", true);
        }else{
            animator.SetBool("jump", false);
        }
    }


    public void Run()
    {
        if (nowAnimation.name.Contains("Attack"))
        {
            activeMoveSpeed = 0f;
            return;
        }

        //ï¿½ï¿½ï¿½Vï¿½tï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½ÍƒXï¿½sï¿½[ï¿½hï¿½ï¿½Ø‚ï¿½Ö‚ï¿½ï¿½ï¿½
        if (Input.GetKey(KeyCode.A) || Input.GetKey(KeyCode.D) || Input.GetKey(KeyCode.S) || Input.GetKey(KeyCode.W))
        {
            if (Input.GetKey(KeyCode.LeftShift))
            {
                activeMoveSpeed = runSpeed;
            }
            else
            {
                activeMoveSpeed = walkSpeed;
            }
        }
        else
        {
            activeMoveSpeed = stopSpeed;
        }
        animator.SetFloat("speed", activeMoveSpeed);
    }



    public void UpdateCursorLock()
    {
        //ï¿½ï¿½ï¿½Í‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½cursorLockï¿½ï¿½Ø‚ï¿½Ö‚ï¿½ï¿½ï¿½
        if (Input.GetKeyDown(KeyCode.Escape))
        {
            cursorLock = false;
        }
        else if (Input.GetMouseButton(0))
        {
            cursorLock = true;
        }

        //cursorLockï¿½ï¿½ï¿½ï¿½ÅƒJï¿½[ï¿½\ï¿½ï¿½ï¿½Ì•\ï¿½ï¿½ï¿½ï¿½Ø‚ï¿½Ö‚ï¿½ï¿½ï¿½
        if (cursorLock)
        {
            //ï¿½Jï¿½[ï¿½\ï¿½ï¿½ï¿½ğ’†‰ï¿½ï¿½ÉŒÅ’è‚µï¿½Aï¿½ï¿½\ï¿½ï¿½ï¿½@https://docs.unity3d.com/ScriptReference/CursorLockMode.html
            Cursor.lockState = CursorLockMode.Locked;
        }
        else
        {
            //ï¿½\ï¿½ï¿½
            Cursor.lockState = CursorLockMode.None;
        }
    }


    /// <summary>
    /// ï¿½eï¿½ÌØ‚ï¿½Ö‚ï¿½ï¿½Lï¿½[ï¿½ï¿½ï¿½Í‚ï¿½ï¿½ï¿½ï¿½mï¿½ï¿½ï¿½ï¿½
    /// </summary>

    /// <summary>
    /// ï¿½eï¿½ÌØ‚ï¿½Ö‚ï¿½
    /// </summary>



    public float GetDamage(AnimationClip hitAttack)
    {
        float damage;
        if (!Motion_Damage.TryGetValue(hitAttack, out damage)) 
            damage = -1;

        return damage;
    }
    private void Attack()
    {
        animator.SetBool("Attack", Input.GetMouseButton(0));
    }

}